'use client';
import { useState } from 'react';
import { Waves, BedDouble, Bath, Users, Wifi, Car, Snowflake, UtensilsCrossed, MapPin, ArrowUpRight, Menu, X, ChevronLeft, ChevronRight } from 'lucide-react';

const imgs = [
'/images/WhatsApp Image 2026-10-02 at 22.56.07 (8).jpeg','/images/WhatsApp Image 2026-10-02 at 22.56.09 (6).jpeg','/images/WhatsApp Image 2026-10-02 at 22.56.06 (1).jpeg','/images/WhatsApp Image 2026-10-02 at 22.56.09 (2).jpeg','/images/WhatsApp Image 2026-10-02 at 22.56.08 (7).jpeg','/images/WhatsApp Image 2026-10-02 at 22.56.09 (1).jpeg','/images/WhatsApp Image 2026-10-02 at 22.56.07 (3).jpeg','/images/WhatsApp Image 2026-10-02 at 22.56.06 (5).jpeg','/images/WhatsApp Image 2026-10-02 at 22.56.08 (3).jpeg'];
const booking='https://www.booking.com/hotel/cy/akame-luxury-beach-villa-by-nomads-private-pool-amp-jacuzzi.html';
export default function Home(){
 const [menu,setMenu]=useState(false); const [light,setLight]=useState<number|null>(null); const [sent,setSent]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); setSent('Sending…'); const f=new FormData(e.currentTarget); const r=await fetch('/api/inquiry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))}); setSent(r.ok?'Thank you — your inquiry has been received.':'Please try again.'); if(r.ok)e.currentTarget.reset();}
 return <main>
  <header className="nav"><a className="brand" href="#top"><span>AKAMÉ</span><small>BEACH VILLA · CYPRUS</small></a><nav className={menu?'links open':'links'}>{['Villa','Gallery','Amenities','Location','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}</a>)}<a className="book" href={booking} target="_blank">Book your stay <ArrowUpRight size={15}/></a></nav><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
  <section id="top" className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(10,20,18,.56),rgba(10,20,18,.05)),url("${imgs[0]}")`}}><div className="heroCopy"><p className="eyebrow">AKAMAS · CYPRUS</p><h1>Where the wild<br/><em>meets the refined.</em></h1><p>A private beach escape shaped by Mediterranean light, quiet luxury and the untamed beauty of Akamas.</p><div className="actions"><a className="primary" href={booking} target="_blank">Book your stay <ArrowUpRight size={17}/></a><a className="ghost" href="#villa">Discover Akamé</a></div></div><div className="facts"><span><Users/>Up to 8 guests</span><span><BedDouble/>4 bedrooms</span><span><Bath/>4 bathrooms</span><span><Waves/>Private pool & jacuzzi</span></div></section>
  <section id="villa" className="intro section"><div><p className="eyebrow dark">THE VILLA</p><h2>A slower rhythm,<br/><em>by the sea.</em></h2></div><div className="copy"><p>Akamé is a contemporary private villa designed for effortless days between sea, pool and sky. Generous indoor-outdoor spaces create a calm base for families and friends exploring the Akamas coast.</p><p>Wake slowly, swim before breakfast, gather around the table at sunset, then retreat to the rooftop jacuzzi as the Mediterranean turns gold.</p><a href="#gallery">Explore the villa ↓</a></div></section>
  <section className="featureGrid"><img src={imgs[1]} alt="Akamé Villa"/><div className="featureText"><p className="eyebrow dark">PRIVATE ESCAPE</p><h2>Made for<br/><em>unhurried days.</em></h2><p>Clean architecture, natural textures and generous outdoor living put the landscape at the centre of every stay.</p><div className="mini"><span>Private pool</span><span>Rooftop jacuzzi</span><span>Outdoor dining</span><span>Landscaped garden</span></div></div></section>
  <section id="gallery" className="section gallery"><div className="sectionHead"><div><p className="eyebrow dark">GALLERY</p><h2>Inside <em>Akamé.</em></h2></div><p>Spaces designed to feel open, tactile and connected to the Mediterranean landscape.</p></div><div className="mosaic">{imgs.slice(2,8).map((src,i)=><button key={src} className={'g'+i} onClick={()=>setLight(i+2)}><img src={src} alt={`Akamé Villa gallery ${i+1}`}/><span>View</span></button>)}</div></section>
  <section id="amenities" className="amenities section"><p className="eyebrow">EVERYTHING YOU NEED</p><h2>Comfort, <em>considered.</em></h2><div className="amenityGrid">{[[Waves,'Private pool'],[Waves,'Rooftop jacuzzi'],[Wifi,'High-speed Wi-Fi'],[Snowflake,'Air conditioning'],[UtensilsCrossed,'Equipped kitchen'],[Car,'Private parking'],[BedDouble,'4 bedrooms'],[Bath,'4 bathrooms']].map(([Icon,label]:any)=><div key={label}><Icon/><span>{label}</span></div>)}</div></section>
  <section id="location" className="location section"><div className="locationCard"><p className="eyebrow dark">THE AKAMAS COAST</p><h2>At the edge of<br/><em>something wild.</em></h2><p>Set in Polis Chrysochous, Akamé places you close to Latchi and the dramatic landscapes of the Akamas Peninsula — one of Cyprus's most distinctive coastal escapes.</p><a className="textLink" href="https://maps.google.com/?q=Polis+Chrysochous+Cyprus" target="_blank"><MapPin size={18}/> Explore the area <ArrowUpRight size={16}/></a></div><img src={imgs[8]} alt="Akamé surroundings"/></section>
  <section className="quote"><p>“Some places are visited.<br/><em>Others are felt.</em>”</p><span>— AKAMÉ</span></section>
  <section id="contact" className="contact section"><div><p className="eyebrow dark">CONTACT</p><h2>Your escape<br/><em>starts here.</em></h2><p>Have a question before you book? Send us a note and we'll help with the details of your stay.</p><a className="primary darkBtn" href={booking} target="_blank">Check availability <ArrowUpRight size={17}/></a></div><form onSubmit={submit}><label>Name<input name="name" required placeholder="Your name"/></label><label>Email<input name="email" type="email" required placeholder="you@email.com"/></label><label>Message<textarea name="message" required placeholder="Tell us about your stay…"/></label><button className="primary" type="submit">Send inquiry <ArrowUpRight size={17}/></button><p className="status">{sent}</p></form></section>
  <footer><div className="brand"><span>AKAMÉ</span><small>LUXURY BEACH VILLA · CYPRUS</small></div><p>Private pool · Jacuzzi · Akamas coast</p><a href="#top">Back to top ↑</a></footer>
  {light!==null&&<div className="lightbox" onClick={()=>setLight(null)}><button className="close" onClick={()=>setLight(null)}><X/></button><button className="prev" onClick={e=>{e.stopPropagation();setLight((light-1+imgs.length)%imgs.length)}}><ChevronLeft/></button><img src={imgs[light]} alt="Akamé Villa enlarged" onClick={e=>e.stopPropagation()}/><button className="next" onClick={e=>{e.stopPropagation();setLight((light+1)%imgs.length)}}><ChevronRight/></button></div>}
 </main>
}
